docker: try to avoid docker failure on container restart.
Currntly from time to time we get this error when restarting services
on cleanup:

raise SSHCalledProcessError(temp_ex.returncode, temp_ex.cmd, temp_ex.output, temp_ex.stderr, self._host)
automation_infra.plugins.ssh_direct.SSHCalledProcessError: Command '/usr/bin/docker ps -a --format ".Names" --filter Name=".reid-grpc-server_."| xargs --no-run-if-empty /usr/bin/docker restart' on host 54.74.65.99 returned non-zero exit status 123
stdout:
stderr: Error response from daemon: Cannot restart container compose_v2_reid-grpc-server_1: driver failed programming external connectivity on endpoint compose_v2_reid-grpc-server_1

This can be caused because either of 2 things:
  1) Something else opens connection on this port and therefore restart
cannot actually start the container (it can be a tunnel)
  2) There is some issue with docker that from time to time restart can
fail.

In order to understand and possible overcome we add defensive code that
will first dump all connections on this port (we will be able to
understand which one) and also stop/start container in case of failure.

Issue: TMTNNFR-481