plugins/memsql: setdefault kwargs instead of adding them
Previously this was causing error:
TypeError: Connect() got multiple values for keyword argument 'cursorclass'